In [1]:
import numpy as np

In [9]:
#Normalization Problem
# Create a random 5x5 ndarray
X = np.random.rand(5, 5)
X

array([[0.34552322, 0.73309457, 0.07701961, 0.36533864, 0.64780238],
       [0.06650283, 0.53218399, 0.08156557, 0.32455791, 0.78668869],
       [0.45240138, 0.76976762, 0.27934448, 0.22263118, 0.87003168],
       [0.14593199, 0.52342238, 0.70914959, 0.51532793, 0.03156278],
       [0.78004448, 0.89537084, 0.31903631, 0.44489857, 0.94265406]])

In [8]:
# Normalize X
X_normalized = (X - X.mean()) / X.std()
X_normalized

array([[-1.48272693,  0.79453791, -1.62520832,  0.49273947,  0.56611099],
       [-1.30973754,  0.01810512, -0.46262627, -1.58394136,  1.2499532 ],
       [-0.78797639,  0.94008929,  1.2997034 ,  0.10742396,  0.80964266],
       [ 0.65888834,  1.35677546, -0.22445027,  0.38281048, -1.24072045],
       [ 0.64274694, -1.55596891,  1.42953763, -0.0125758 , -0.46313261]])

In [5]:
# Save normalized array
np.save('X_normalized.npy', X_normalized)

In [7]:
#DIVISIBLE BY 3 PROBLEM:
# Create ndarray of squares of first 100 positive integers
A = np.arange(1, 101) ** 2
A = A.reshape(10, 10)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [12]:
# Elements divisible by 3
div_by_3 = A[A % 3 == 0]
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [13]:
# Save the file
np.save('div_by_3.npy', div_by_3)